uploads = []
generated = []

[[outputs]]
id = "YWlDBJLWKH2tQYYzcA18u"
uri = "file://TESTING.md"
type = "text"
title = "Checklist de validación"

[[outputs]]
id = "yLmVQmNCoUMr37eOWIIQm"
uri = "file://BACKLOG.md"
type = "text"
title = "Backlog de tareas"
