import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import agenciesRouter from "./agencies";
import usersRouter from "./users";
import hotelsRouter from "./hotels";
import activitiesRouter from "./activities";
import itinerariesRouter from "./itineraries";
import tripsRouter from "./trips";
import invitationsRouter from "./invitations";
import travelerRouter from "./traveler";
import dashboardRouter from "./dashboard";
import destinationsRouter from "./destinations";
import storageRouter from "./storage";
import checklistTemplatesRouter from "./checklist-templates";
import travelerProfilesRouter from "./traveler-profiles";
import searchRouter from "./search";
import agencyPublicRouter from "./agency-public";
import agencyInquiriesRouter from "./agency-inquiries";

const router: IRouter = Router();

router.use(healthRouter);
router.use(searchRouter);
router.use(agencyPublicRouter);
router.use(authRouter);
router.use(agenciesRouter);
router.use(usersRouter);
router.use(hotelsRouter);
router.use(activitiesRouter);
router.use(itinerariesRouter);
router.use(tripsRouter);
router.use(invitationsRouter);
router.use(travelerRouter);
router.use(dashboardRouter);
router.use(destinationsRouter);
router.use(storageRouter);
router.use(checklistTemplatesRouter);
router.use(travelerProfilesRouter);
router.use(agencyInquiriesRouter);

export default router;
